"""initial migration

Revision ID: 66737dd498a4
Revises: 
Create Date: 2018-07-07 02:03:39.294758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66737dd498a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('bookmarkname', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('bookmarkname'),
    sa.UniqueConstraint('bookmarkname'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('widget_a', sa.String(length=150), nullable=True),
    sa.Column('widget_b', sa.String(length=150), nullable=True),
    sa.Column('widget_c', sa.String(length=150), nullable=True),
    sa.Column('widget_d', sa.String(length=150), nullable=True),
    sa.Column('widget_e', sa.String(length=150), nullable=True),
    sa.Column('widget_f', sa.String(length=150), nullable=True),
    sa.Column('widget_g', sa.String(length=150), nullable=True),
    sa.Column('widget_h', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
